staticman:
  allowedFields: ['name', 'email', 'comment']
  requiredFields: ['name', 'comment']
  branch: 'master'
  format: 'yaml'
  moderation: true
  path: _data/posts/{options.post-slug}
  transforms:
    email: 'md5'
  generatedFields:
    myField:
      type: date
      options:
        format: timestamp
